style = default

maxColumn = 120

optIn.breakChainOnFirstMethodDot = true
//includeNoParensInSelectChains = true
docstrings = ScalaDoc

align = most
align.openParenCallSite = true
align.openParenDefnSite = false

align.tokens.add = [
  "=", ":", "%", "%%", ",", "⇒", "=>"
]

assumeStandardLibraryStripMargin = true
align.stripMargin = true
newlines.beforeCurlyLambdaParams = multilineWithCaseOnly
newlines.avoidForSimpleOverflow = [tooLong]

continuationIndent.defnSite = 2
//verticalMultiline.atDefnSite = true
//verticalMultiline.arityThreshold = 2
//verticalMultiline.newlineAfterOpenParen = true

danglingParentheses = true

rewrite {
  rules = [
    AvoidInfix
    RedundantParens
    RedundantBraces
    AsciiSortImports
    PreferCurlyFors
    SortModifiers
  ]

  redundantBraces.maxLines = 1
}

rewriteTokens = {
  "=>": "⇒"
  "->": "→"
  "<-": "←"
}

version=2.7.2
