#release configuration
#Mon Jun 30 18:38:06 IST 2025
projectVersionPolicyId=default
project.scm.io.github.sparkplusplus\:sparkplusplus.tag=HEAD
scm.branchCommitComment=@{prefix} prepare branch @{releaseLabel}
pinExternals=false
projectVersionPolicyConfig=<projectVersionPolicyConfig>${projectVersionPolicyConfig}</projectVersionPolicyConfig>\n
pushChanges=true
project.scm.io.github.sparkplusplus\:sparkplusplus.developerConnection=scm\:git\:https\://github.com/sparkplusplus/sparkplusplus.git
project.scm.io.github.sparkplusplus\:sparkplusplus.connection=scm\:git\:git\://github.com/sparkplusplus/sparkplusplus.git
scm.rollbackCommitComment=@{prefix} rollback the release of @{releaseLabel}
remoteTagging=true
scm.commentPrefix=[release]
releaseStrategyId=default
project.scm.io.github.sparkplusplus\:sparkplusplus.url=https\://github.com/sparkplusplus/sparkplusplus
completedPhase=scm-commit-release
scm.url=scm\:git\:https\://github.com/sparkplusplus/sparkplusplus.git
scm.developmentCommitComment=@{prefix} prepare for next development iteration
scm.tagNameFormat=@{project.artifactId}-@{project.version}
scm.tag=sparkplusplus-0.0.1
project.dev.io.github.sparkplusplus\:sparkplusplus=0.0.2-SNAPSHOT
project.rel.io.github.sparkplusplus\:sparkplusplus=0.0.1
exec.snapshotReleasePluginAllowed=false
preparationGoals=clean verify
scm.releaseCommitComment=@{prefix} prepare release @{releaseLabel}
exec.pomFileName=pom.xml
